Repository cherryontech/website, pull requests merged in 2020-10, with the labels that each got.

#56 Add contributing guidelines
  CONTRIBUTING.md
  README.md
Labels: Ready for test

#84 Added Allie's OctoCat
  uploads/allie.jpg
Labels: Ready for merge

#80 Remove pagination, sort dict entries
  src/pages/Dictionary.vue
Labels: Ready for merge

#86 CT logos
  src/assets/images/CT  round logo pink and green.png
  src/assets/images/CT logo  green and yellow .png
  src/assets/images/CT logo pink and green.png
Labels: Ready for merge

#91 Create brand-deck.md in dictionary
  content/dictionary/brand-deck.md
Labels: Ready for merge

#81 Feat/dict filtering
  src/components/controls/base/BaseInput.vue
  src/pages/Dictionary.vue
Labels: bug

#98 updated Android.md with definition
  content/dictionary/android.md
Labels: Ready for merge

#97 Update analytics.md with definition
  content/dictionary/analytics.md
Labels: Ready for merge
